version: "3.8"

services:
  interlock-frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: interlock-frontend
    container_name: interlock-frontend
    restart: unless-stopped
    networks:
      - interlock-network
    env_file: ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    hostname: interlock-frontend
    ports:
      - ${PORT:-5177}:5177

networks:
  interlock-network:
    external: true
    driver: bridge
